<a href="https://colab.research.google.com/github/msymhkr/mainopen/blob/main/M6P.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<<Number Prediction - Method 1>>

In [3]:
# Method 1
from tensorflow.keras.models import Sequential
from tensorflow.keras import layers
from tensorflow.keras.layers import LSTM, Dense
from sklearn.preprocessing import StandardScaler
import numpy as np
import pandas as pd

# file_path = "/content/Colab - Final Mark Six Result List 2024 - 2003.csv"
file_path = "/content/sample_data/Colab - Final Mark Six Result List 2024 - 2003.csv"
data = pd.read_csv(file_path)
# data.to_csv(file_path, index= False, header= True)
data = data.drop('Volume', axis=1)
data1 = data.drop('Date', axis=1)
# data.drop(data.tail(2570).index, inplace=True)

# normalize array
max_number = np.max(data1)
t_data = np.divide(data1, max_number)
t_data = t_data.to_numpy()

time_steps = 1  # each row as one time step
num_features = t_data.shape[1]  # Number of features, in our case 7
X_train = np.reshape(t_data, (t_data.shape[0], time_steps, num_features))
model = Sequential()
model.add(LSTM(50, activation='relu', input_shape=(time_steps, num_features)))
model.add(Dense(4))
model.compile(optimizer='adam', loss='mse')

print("sssssssssssssss")
# print(t_data(type))
print(t_data[0:, 0:4])
model.fit(X_train, t_data[0:, 0:4], epochs=100, batch_size=32)
model.save('M6Predict-1.h5')

# example_input: replace it with real input data
example_input = np.array([[23, 17, 34, 1, 22, 30]])
normalized_input = np.divide(example_input, max_number)
X_predict = np.reshape(normalized_input, (time_steps, num_features))
# making predictions
predicted_numbers = model.predict(X_predict)
# denormalizing and rounding the numbers
actual_predictions = np.round(predicted_numbers * max_number).astype(int)
# the first 4 numbers are our predictions
predicted_lottery_numbers = actual_predictions[0, :4]
print("Predicted lottery numbers:", predicted_lottery_numbers)


sssssssssssssss
[[0.10204082 0.12244898 0.32653061 0.46938776]
 [0.18367347 0.20408163 0.24489796 0.53061224]
 [0.16326531 0.34693878 0.42857143 0.44897959]
 ...
 [0.10204082 0.26530612 0.44897959 0.55102041]
 [0.16326531 0.28571429 0.40816327 0.57142857]
 [0.02040816 0.06122449 0.14285714 0.3877551 ]]
Epoch 1/100


/usr/local/lib/python3.10/dist-packages/keras/src/layers/rnn/rnn.py:204: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


96/96 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 0.0933
Epoch 2/100
96/96 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.0104
Epoch 3/100
96/96 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.0065
Epoch 4/100
96/96 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.0037
Epoch 5/100
96/96 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.0023
Epoch 6/100
96/96 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.0014
Epoch 7/100
96/96 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 9.5793e-04
Epoch 8/100
96/96 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.9666e-04
Epoch 9/100
96/96 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 4.8130e-04
Epoch 10/100
96/96 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 3.0514e-04
Epoch 11/100
96/96 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 1.8856e-04
Epoch 12/100
96/96 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 1.2701e-04
Epoch 13/100
96/96 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9.3700e-05
Epoch 14/100
96/96 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8.3575e-05
Epoch 15/100
96/96 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step

ValueError: cannot reshape array of size 6 into shape (1,7)

In [9]:
# Method 2 (incomplete)
from tensorflow.keras.models import Sequential
from tensorflow.keras import layers
from tensorflow.keras.layers import LSTM, Dense
from sklearn.preprocessing import StandardScaler
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt

# file_path = "/content/Colab - Final Mark Six Result List 2024 - 2003.csv"
file_path = "/content/sample_data/Colab - Final Mark Six Result List 2024 - 2003.csv"
data3 = pd.read_csv(file_path)
data2 = data3.drop('Volume', axis=1)
data = data2.drop('Date', axis=1)

scaler = StandardScaler().fit(data.values)
transformed_dataset = scaler.transform(data.values)
t_data = pd.DataFrame(data=transformed_dataset, index=data.index)
# print(t_data)

train_size = int(len(t_data) * 0.8)
train_data, test_data = t_data[:train_size], t_data[train_size:]

def create_sequences(dt, look_back):
  X, y = [], []
  for i in range(0, (len(dt) - look_back - 1)):
      seq1 = dt[i:(i + look_back)]
      X.append(seq1)
      seq2 = dt[(i + look_back): (i + look_back) + 1]
      y.append(seq2)
  return np.array(X), np.array(y)

look_back = 10
X_train, y_train = create_sequences(train_data, look_back)
X_test, y_test = create_sequences(test_data, look_back)

# print(X_train.shape)
# print(X_train[2])
# X_train = np.reshape(X_train, (X_train.shape[0], X_train.shape[1], 1))
# X_test = np.reshape(X_test, (X_test.shape[0], X_test.shape[1], 1))
# print(11111)
# print(X_test.shape)

model = Sequential()
model.add(LSTM(50, input_shape=(look_back, 7)))
model.add(Dense(1, activation='sigmoid'))
model.summary()
model.compile(loss='mean_squared_error', optimizer='adam', metrics=['acc'])
history = model.fit(X_train, y_train, epochs=100, batch_size=50, verbose=2)
model.save('M6Predict-2.h5')

train_loss = model.evaluate(X_train, y_train, verbose=0)
test_loss = model.evaluate(X_test, y_test, verbose=0)
print(f'Train loss: {train_loss}')
print(f'Test loss: {test_loss}')

train_preds = model.predict(X_train)
test_preds = model.predict(X_test)

plt.plot(history.history,
    ['loss', 'val_loss'],
    title='Training & Validation Loss',
    xyLabel=['Epoch', 'Loss'])
plt.plot(history.history,
    ['acc', 'val_acc'],
    title='Training & Validation Accuracy',
    xyLabel=['Epoch', 'Loss'])

# input last 10 rows data for prediction?????????????
# example_input = np.array([[23, 17, 34, 1, 22, 30, 47]])
example_input = np.array(t_data[-10])
normalized_input = example_input / max_number
X_predict = np.reshape(normalized_input, (time_steps, num_features))
predicted_numbers = model.predict(0, X_predict)
actual_predictions = np.round(predicted_numbers * max_number).astype(int)
# the first 4 numbers are our predictions
predicted_lottery_numbers = actual_predictions[0, :4]
print("Predicted lottery numbers:", predicted_lottery_numbers)


KeyError: -10